### ISSUE TITLE
Not an Issue -- Not sure how to contact you.

### ISSUE THREAD

**Issue by losthearts** [succumbs/convert-sens#1]
Hi! I was browsing through GitHub (as one does), when I came across your GitHub repository.

I was then tempted to create my own version of what you are trying to do, in Golang. 
The GitHub repository for my project is at [losthearts/Sensaina](https://github.com/losthearts/Sensaina). 

You are doing an amazing job yourself.

**Comment by succumbs** [comment]
thank you so much! yours looks awesome too!

**Comment by losthearts** [comment]
Thanks for the reply! I just released a package. I shall close this issue now, I hope you are able to make a program that satisfies your expectations :)
